language: node_js
script: npm run coverage
node_js:
    - "12"
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
after_success:
  - bash <(curl -s https://codecov.io/bash)
